services:
  api:
    image: mercadona-ticket-analyzer:local
    build:
      context: .
      target: development
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
        - action: rebuild
          path: poetry.lock
    ports:
      - 8000:8000
    volumes:
      - .:/app
